//! Shared shape for "install X / uninstall X by name(s)" commands backed by
//! a blocking `fn(config_dir: &str, names: &[&str]) -> mx::Result<()>` pair
//! from `modulix-core-utils`.

/// Generate a pair of [`Command`](super::Command) implementations for
/// installing and uninstalling one or more things identified by name.
///
/// # Parameters (macro arguments)
/// * `$install` - identifier for the generated "install" struct; also its
///   D-Bus method name, via `stringify!($install)` (e.g. `InstallPackage`).
/// * `$uninstall` - identifier for the generated "uninstall" struct; also
///   its D-Bus method name, via `stringify!($uninstall)`.
/// * `$kind` - string literal noun used in the log message
///   (`"installing "`/`"uninstalling "` + `$kind`) and spliced into the
///   returned status string (`"<$kind> {names} installed"` /
///   `"<$kind> {names} uninstalled"`).
/// * `$install_fn` - path to the blocking `modulix-core-utils` function
///   called to install, with signature
///   `fn(config_dir: &str, names: &[&str]) -> mx::Result<()>`; invoked once
///   for the *whole* argument list via `tokio::task::spawn_blocking`.
/// * `$uninstall_fn` - same shape as `$install_fn`, for uninstalling.
///
/// # Pre-conditions
/// `Command` and `Error` (this crate's [`crate::error::Error`]) must be in
/// scope at the call site.
///
/// # Generated items
/// Two unit structs, `$install` and `$uninstall`, each implementing
/// [`Command`](super::Command). For both:
/// * [`Command::name`](super::Command::name) returns `stringify!($install)`
///   / `stringify!($uninstall)` - the exact D-Bus method name the struct
///   serves (e.g. `InstallPackage`/`UninstallPackage`).
/// * [`Command::execute`](super::Command::execute)'s `arguments` holds one
///   name per element (e.g. nixpkgs attribute names); the whole slice is
///   forwarded in a **single call** to `$install_fn`/`$uninstall_fn`, so all
///   the names are applied as **one transaction** with **one
///   `nixos-rebuild`** covering the whole batch - not one transaction per
///   name. Consequently, if the underlying transaction fails partway
///   through (e.g. an unknown nixpkgs attribute rejected during the
///   `nixos-rebuild switch` evaluation), the configuration is rolled back as
///   a whole and *none* of the names end up applied, even the ones that
///   would individually have succeeded.
///   The call blocks for the entire duration of that `nixos-rebuild`
///   (potentially minutes). It is skipped entirely - only the info log and
///   the status string are produced - when [`crate::dry_run::is_dry_run`]
///   is `true`.
/// * On success, `execute` returns `Ok(format!("{$kind} {names} installed"))`
///   / `Ok(format!("{$kind} {names} uninstalled"))`, where `names` is
///   `arguments.join(", ")` - this exact string is also what gets logged.
///
/// # Errors
/// `execute` returns [`crate::error::Error::CoreUtils`] if the
/// `spawn_blocking` task panics/is cancelled, or if `$install_fn`/
/// `$uninstall_fn` itself returns an error.
#[macro_export]
macro_rules! lifecycle_commands {
    ($install:ident, $uninstall:ident, $kind:literal, $install_fn:path, $uninstall_fn:path) => {
        #[doc = concat!(
            "Install one or more ", $kind, "s by name.\n\n",
            "Generated by [`lifecycle_commands`](crate::lifecycle_commands); ",
            "see that macro's documentation for the exact D-Bus method name, ",
            "argument layout, transaction/dry-run behaviour and status string ",
            "this implementation follows.",
        )]
        pub struct $install;

        #[async_trait::async_trait]
        impl Command for $install {
            /// D-Bus method name this command serves; see
            /// [`lifecycle_commands`](crate::lifecycle_commands).
            ///
            /// # Returns
            /// `stringify!($install)`.
            fn name(&self) -> &'static str {
                stringify!($install)
            }

            /// Installs every name in `arguments` as one transaction; see
            /// [`lifecycle_commands`](crate::lifecycle_commands) for the full
            /// contract (arguments layout, transaction granularity,
            /// dry-run skip, exact status string).
            ///
            /// # Parameters
            /// * `arguments` - one name per element, all forwarded together
            ///   to the install library call.
            ///
            /// # Returns
            /// `concat!($kind, " {names} installed")` with `names` the
            /// comma-joined `arguments`.
            ///
            /// # Errors
            /// [`Error::CoreUtils`] if the blocking task panics/is
            /// cancelled or if the library call fails.
            async fn execute(&self, arguments: &[&str]) -> Result<String, Error> {
                let names = arguments.join(", ");

                tracing::info!(names = %names, concat!("installing ", $kind));

                if !$crate::dry_run::is_dry_run() {
                    let owned: Vec<String> = arguments.iter().map(|s| s.to_string()).collect();
                    tokio::task::spawn_blocking(move || {
                        let refs: Vec<&str> = owned.iter().map(String::as_str).collect();
                        $install_fn($crate::config_dir::config_dir(), &refs)
                    })
                    .await
                    .map_err(|e| Error::CoreUtils(e.to_string()))?
                    .map_err(|e| Error::CoreUtils(e.to_string()))?;
                }

                Ok(format!(concat!($kind, " {} installed"), names))
            }
        }

        #[doc = concat!(
            "Uninstall one or more ", $kind, "s by name.\n\n",
            "Generated by [`lifecycle_commands`](crate::lifecycle_commands); ",
            "see that macro's documentation for the exact D-Bus method name, ",
            "argument layout, transaction/dry-run behaviour and status string ",
            "this implementation follows.",
        )]
        pub struct $uninstall;

        #[async_trait::async_trait]
        impl Command for $uninstall {
            /// D-Bus method name this command serves; see
            /// [`lifecycle_commands`](crate::lifecycle_commands).
            ///
            /// # Returns
            /// `stringify!($uninstall)`.
            fn name(&self) -> &'static str {
                stringify!($uninstall)
            }

            /// Uninstalls every name in `arguments` as one transaction; see
            /// [`lifecycle_commands`](crate::lifecycle_commands) for the full
            /// contract (arguments layout, transaction granularity,
            /// dry-run skip, exact status string).
            ///
            /// # Parameters
            /// * `arguments` - one name per element, all forwarded together
            ///   to the uninstall library call.
            ///
            /// # Returns
            /// `concat!($kind, " {names} uninstalled")` with `names` the
            /// comma-joined `arguments`.
            ///
            /// # Errors
            /// [`Error::CoreUtils`] if the blocking task panics/is
            /// cancelled or if the library call fails.
            async fn execute(&self, arguments: &[&str]) -> Result<String, Error> {
                let names = arguments.join(", ");

                tracing::info!(names = %names, concat!("uninstalling ", $kind));

                if !$crate::dry_run::is_dry_run() {
                    let owned: Vec<String> = arguments.iter().map(|s| s.to_string()).collect();
                    tokio::task::spawn_blocking(move || {
                        let refs: Vec<&str> = owned.iter().map(String::as_str).collect();
                        $uninstall_fn($crate::config_dir::config_dir(), &refs)
                    })
                    .await
                    .map_err(|e| Error::CoreUtils(e.to_string()))?
                    .map_err(|e| Error::CoreUtils(e.to_string()))?;
                }

                Ok(format!(concat!($kind, " {} uninstalled"), names))
            }
        }
    };
}
