//! Install/uninstall a system package by name.
//!
//! Generated by [`lifecycle_commands`] below,
//! wired to the `modulix-core-utils` `install_package` functions. Serves the
//! `InstallPackage`/`UninstallPackage` D-Bus methods; `arguments` holds one
//! nixpkgs attribute name per element (e.g. `"firefox"`, or `"firefox.dev"`
//! to request a specific output). All names are forwarded together to
//! [`modulix_core_utils::install_package::install`]/[`modulix_core_utils::install_package::uninstall`]
//! in a **single call**, so the whole batch is applied as **one transaction**
//! with **one `nixos-rebuild switch`** - if any name in the batch fails
//! (e.g. an unknown attribute), the transaction rolls back as a whole and
//! *none* of the packages end up installed/uninstalled, not just the failing
//! one. That call blocks for the entire duration of the rebuild (can be
//! minutes) and is skipped - only logged - when
//! [`crate::dry_run::is_dry_run`] is true. On success the returned status
//! string is `"package {names} installed"` / `"package {names} uninstalled"`,
//! with `names` the comma-joined argument list.

use crate::lifecycle_commands;

use super::Command;
use crate::error::Error;

lifecycle_commands!(
    InstallPackage,
    UninstallPackage,
    "package",
    modulix_core_utils::install_package::install,
    modulix_core_utils::install_package::uninstall
);

#[cfg(test)]
#[path = "package-tests.rs"]
mod tests;
